services:

  click:
    image: clickhouse/clickhouse-server
    container_name: click
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - 8123:8123
    env_file:
      - ./envs.sh

  vector:
    image: timberio/vector:latest-debian
    container_name: vector
    volumes:
      - ./vector.yaml:/etc/vector/vector.yaml
      - ./logs:/logs
    ports:
      - 8686:8686
    env_file:
      - ./envs.sh
